### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by santosh** [gophercises/task#7]
My `main.go`:

```go
func main() {
	home, _ := homedir.Dir()
	dbPath := filepath.Join(home, "tasks.db")
	doOrQuit(db.Init(dbPath))
	doOrQuit(cmd.RootCmd.Execute())
}

func doOrQuit(err error) {
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(1)
	}
}
```
My `db/tasks.go`:

```go
var taskBucket = []byte("tasks")

var db *bolt.DB

type Task struct {
	Key   int
	Value string
}

// Init creates db file and create appropriate bucket if
// not already exists. This is required for inserts later on.
func Init(dbPath string) error {
	var err error
	db, err := bolt.Open(dbPath, 0600, nil)
	if err != nil {
		return err
	}
	return db.Update(func(tx *bolt.Tx) error {
		_, err := tx.CreateBucketIfNotExists(taskBucket)
		return err
	})
}

func CreateTask(task string) (int, error) {
	var id int
	err := db.Update(func(tx *bolt.Tx) error {
		b := tx.Bucket(taskBucket)
		id64, _ := b.NextSequence()
		id = int(id64)
		key := itob(id)
		return b.Put(key, []byte(task))
	})
	if err != nil {
		// expose error to the caller
		return -1, err
	}
	return id, nil
}

// itob converts from int to Bolt friendly binary
func itob(v int) []byte {
	b := make([]byte, 8)
	binary.BigEndian.PutUint64(b, uint64(v))
	return b
}

// btoi converts from byte to int
func btoi(b []byte) int {
    return int(binary.BigEndian.Uint64(b))
}
```

`cmd/add.go`:

```go
var addCmd = &cobra.Command{
	Use:   "add",
	Short: "Adds a task to your task list.",
	Run: func(cmd *cobra.Command, args []string) {
		task := strings.Join(args, " ")
		_, err := db.CreateTask(task)
		if err != nil {
			fmt.Println("Something went wrong: ", err.Error())
			return
		}
		fmt.Printf("Added \"%s\" to your task list.\n", task)
	},
}

func init() {
	RootCmd.AddCommand(addCmd)
}
```
For some reason, I am getting the above-mentioned panic. Below is the complete traceback.

```bash
$ go install

$ task add please not crash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1d0 pc=0x50db14]

goroutine 1 [running]:
github.com/boltdb/bolt.(*DB).beginRWTx(0x0, 0x0, 0x0, 0x0)
        /home/sntshk/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:506 +0x44
github.com/boltdb/bolt.(*DB).Begin(0x0, 0xc00000e901, 0xc000069420, 0xc000109ca0, 0x5eb740)
        /home/sntshk/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:461 +0x38
github.com/boltdb/bolt.(*DB).Update(0x0, 0xc000109cb0, 0x0, 0x0)
        /home/sntshk/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:582 +0x49
github.com/santosh/task/db.CreateTask(0xc000024950, 0x10, 0x3, 0x8fa918, 0x1)
        /home/sntshk/repos/task/db/tasks.go:37 +0x7b
github.com/santosh/task/cmd.glob..func1(0xcb9e00, 0xc0000919e0, 0x3, 0x3)
        /home/sntshk/repos/task/cmd/add.go:16 +0x91
github.com/spf13/cobra.(*Command).execute(0xcb9e00, 0xc000091980, 0x3, 0x3, 0xcb9e00, 0xc000091980)
        /home/sntshk/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xcba5e0, 0x15, 0x0, 0x0)
        /home/sntshk/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /home/sntshk/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /home/sntshk/repos/task/main.go:17 +0xa3
```

**Comment by joncalhoun** [comment]
Chances are your `Init` function is not getting called so the `var db *bolt.DB` isn't getting initialized, but unfortunately I don't have the capacity to help you debug. My suggestion is to ask in the Gophers slack - https://invite.slack.golangbridge.org/

There are newbie channels and a gophercises channel. I'm guessing someone in one of those could help.

**Comment by santosh** [comment]
For future reference. I asked in one of the channels and was pointed out that...

In `Init` func, I used the walrus operator instead of `=`.

```go
db, err := bolt.Open(dbPath, 0600, nil)

// should be
db, err = bolt.Open(dbPath, 0600, nil)
```
